# Generated by Django 3.0.5 on 2020-04-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('series', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('releaseYear', models.IntegerField(blank=True, null=True)),
                ('isStillProduced', models.BooleanField(blank=True, null=True)),
                ('picName', models.CharField(max_length=256)),
            ],
        ),
    ]
