# Generated by Django 3.0.5 on 2020-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
