# Generated by Django 3.0.5 on 2020-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='picName',
        ),
        migrations.AddField(
            model_name='car',
            name='class_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
