# Generated by Django 3.0.5 on 2020-04-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20200423_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenanswer', models.CharField(blank=True, max_length=256, null=True)),
                ('correctanswer', models.CharField(blank=True, max_length=256, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('rownumber', models.IntegerField(blank=True, null=True)),
                ('sessionid', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
