# Generated by Django 3.0.5 on 2020-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
