# Generated by Django 3.0.5 on 2020-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_game_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
