# Generated by Django 3.0.5 on 2020-04-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20200425_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='correctCart',
            new_name='correctCar',
        ),
    ]
