# Generated by Django 3.0.5 on 2020-04-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_game_modus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='images',
            new_name='image',
        ),
    ]
